# Site settings
title: Amelia Ruslim - ...dwell in possiblity

# Build settings
markdown: kramdown
permalink: pretty

# custom variables
email: amelia.ruslim@gmail.com
linkedin: https://www.linkedin.com/in/ameliaruslim
medium: https://medium.com/@ameeliar
twitter: https://twitter.com/ameeliar
portfolio: https://drive.google.com/file/d/0B4H4MB3nImNheDNUMGVpZnVyRmc/view?usp=sharing
